name: Read package.json

on:
 push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Print something
      run: echo "$GITHUB_REPOSITORY"
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: package.json
    - name: Echo package.json
      run: echo "${{ steps.package.outputs.content }}" 
