name: Read package.json

on:
 push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Print something
      run: echo "$GITHUB_REPOSITORY"
    - name: Read package.json
      id: package
      uses: actions/checkout@v2
      with:
        path: ./README.md
    - name: Echo package.json
      run: echo "meghnasavit"
    - name: something
      run: echo "${{ steps.package.outputs.content }}" 
